### ISSUE TITLE
Found version 4, expected 3, resolving symbol AppModule 

### ISSUE THREAD

**Issue by lesiba7** [Napster2210/ngx-spinner#4] opened 2018-02-21 11:40 UTC
Hi,

I am using Angular 4 and i am getting the following error:
`
node_modules/ngx-spinner/ngx-spinner.d.ts, found version 4, expected 3, resolving symbol AppModule`

I downgraded to all versions but I still get the same error.

Thanks

**Comment by Napster2210** [comment] 2018-02-21 12:06
Such issues are coming now a days due to cli update, will check this one and try to resolve as soon as possible.

**Comment by Napster2210** [comment] 2018-02-21 12:11
@lesiba7 just hit the command `ng -v` and post that information here. I want to know the angular-cli version, nodejs version etc.

**Comment by lesiba7** [comment] 2018-02-21 12:16
```
Your global Angular CLI version (1.5.0) is greater than your local
version (1.4.2). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.4.2
node: 8.9.0
os: darwin x64
@angular/animations: 4.4.2
@angular/common: 4.4.2
@angular/compiler: 4.4.2
@angular/core: 4.4.2
@angular/forms: 4.4.2
@angular/http: 4.4.2
@angular/platform-browser: 4.4.2
@angular/platform-browser-dynamic: 4.4.2
@angular/router: 4.4.2
@angular/cli: 1.4.2
@angular/compiler-cli: 4.4.2
@angular/language-service: 4.4.2
typescript: 2.3.4
```

**Comment by Napster2210** [comment] 2018-02-21 12:18
Thanx will look into it

**Comment by knehez** [comment] 2018-03-07 13:28
Do you know any solutions? I have the same problem. Thanks

**Comment by Napster2210** [comment] 2018-03-07 14:56
@knehez working on it will release new version with fixes soon.

**Comment by Napster2210** [comment] 2018-03-10 18:04
@lesiba7  @knehez can you please try the latest version([v1.1.0](https://github.com/Napster2210/ngx-spinner/releases/tag/v1.1.0))

**Comment by SanchitSahu** [comment] 2018-03-11 23:33
@Napster2210 I am on v1.1.0, still seeing the same error.

**Comment by SanchitSahu** [comment] 2018-03-11 23:37
Is this package only with Angular 5 and plus OR is also supported with Angular2/4?

**Comment by Darkheir** [comment] 2018-03-26 14:48
I think the issue is because you are trying to run the package with angular 4 and now only angular 5 seems to be supported.

When you install the package the `.metadata.json` file of package has a `version` key with the value `4` and angular 4 uses the version `3`

**Comment by Pescu** [comment] 2018-03-26 16:10
@Napster2210 do you have updates? I try v1.1.0 but still doesn't work.

**Comment by bradleyquinn** [comment] 2018-03-28 18:44
This is NOT compatible with anything but Angular 5+, and it has never been.  I've installed packages all the way back to 0.1.7 and the meta version mismatch persists.  Angular 4->5 introduced many non-backward compatible changes, and this error is indicative of that change.

**Comment by Viveckh** [comment] 2018-03-28 22:53
I really loved the demo of this, but sadly couldn't use it due to its incompatibility with Ang 4

**Comment by Napster2210** [comment] 2018-03-29 18:32
I think I have to downgrade the Angular version due to this issue. Any suggestion?

**Comment by Viveckh** [comment] 2018-04-02 12:26
If you'd want more people to use it, downgrade and release at least one version, so people using angular 4 can use that version. And then maybe, you can continue future builds with Ang 5.

**Comment by Napster2210** [comment] 2018-04-03 11:59
@Viveckh @Pescu @lesiba7 @knehez @SanchitSahu @Darkheir 
I have tried to downgrade the version of Angular to V4 but facing problems with build after that. If you guys find any solution of the same and please let em know.

**Comment by Viveckh** [comment] 2018-04-03 13:58
@Napster2210 I'm trying to work on this myself, but I couldn't figure out how to run it upon cloning a copy of the develop branch. What steps do I have to take in order to run the project?

**Comment by Darkheir** [comment] 2018-04-04 12:12
The problem from the file `gulpfile.js`

```js
/**
 * 4. Run the Angular compiler, ngc, on the /.tmp folder. This will output all
 *    compiled modules to the /build folder.
 *
 *    As of Angular 5, ngc accepts an array and no longer returns a promise.
 */
gulp.task('ngc', function () {
  ngc(['--project', `${tmpFolder}/tsconfig.es5.json`]);
  return Promise.resolve()
});
```

This is not supported in angular 4.

```js
/**
 * 4. Run the Angular compiler, ngc, on the /.tmp folder. This will output all
 *    compiled modules to the /build folder.
 *
 *    As of Angular 5, ngc accepts an array and no longer returns a promise.
 */
gulp.task('ngc', function () {
  return ngc({
    project: `${tmpFolder}/tsconfig.es5.json`
  })
  .then((exitCode) => {
    if (exitCode === 1) {
      throw new Error('Compiler error');
    }
  });
});
```

This code is working

**Comment by sudhakar-sekar** [comment] 2018-04-12 08:06
Hi, 
I am also facing same issue. I am using Angular 4.
I downgraded ngx-spinner from v1.1.0 to v0.1.7.
Still I am facing same issue?

**Comment by Nhilo94** [comment] 2018-04-16 12:46
i'm facing the same issue too

**Comment by Napster2210** [comment] 2018-04-16 12:59
I'm working on downgrading the version of Angular. Will release in few days.

**Comment by Napster2210** [comment] 2018-04-21 20:38
Hello @lesiba7 @knehez @SanchitSahu @Darkheir @Pescu @Nhilo94 @sudhakar-sekar @Viveckh @bradleyquinn , 
Can you guys please try version V1.2.0([https://www.npmjs.com/package/ngx-spinner](https://www.npmjs.com/package/ngx-spinner)) and let me know if its working for you or not?
I have downgrade all the Angular dependencies to v4.

**Comment by Viveckh** [comment] 2018-04-21 20:44
@Napster2210 Give me a few minutes, let me test that out real quick. Fingers crossed, hope all goes well.

**Comment by Viveckh** [comment] 2018-04-21 21:29
UPDATE: Great news everyone. Release 1.2.0 works on Angular 4 now. I just tested it within a modular application, along with A-LOT compilation, and everything went smooth. @Napster2210

**Comment by rspl-yuvraj** [comment] 2018-04-22 07:16
@Viveckh thanx for the update. Let's wait some other users, once they tested form their end I'll close this issue and work on some new features.

**Comment by Napster2210** [comment] 2018-04-23 06:59
@Darkheir Thanx for your suggestion. It helps me. Will close this issue in next 2 days.

**Comment by Pescu** [comment] 2018-04-24 11:54
@Napster2210  thanx for the update, now works on angular 4.

**Comment by Napster2210** [comment] 2018-04-25 14:41
> Closing this issue, resolve in **V1.2.0**.

**Closed by Napster2210** 2018-04-25 14:41 UTC
Labels: bug, help wanted

**Comment by sudhakar-sekar** [comment] 2018-06-06 12:39
@Napster2210 Thanks for the update.

**Comment by JFancis** [comment] 2019-07-25 11:29
hello @Napster2210 i want to use ngx-spinner in my projet but
i have this probleme WARNING in ./node_modules/ngx-spinner/fesm5/ngx-spinner.js
208:59-77 "export 'ɵɵdefineInjectable' was not found in '@angular/core'.
My environnement is Angular 6 .
helpe me please ,thanks.

**Comment by Napster2210** [comment] 2019-07-25 12:05
@JFancis which version of `ngx-spinner` you're using? You've to use `7.2.0`
