### ISSUE TITLE
Angular 6 Support

### ISSUE THREAD

**Issue by waguirre** [Napster2210/ngx-spinner#13] opened 2018-05-09 21:47 UTC
In angular 6 with rxjs 6 fix.

**Comment by dn-medroom** [comment] 2018-05-11 16:06
I made a pull request converting...let me know if it helps

**Comment by Napster2210** [comment] 2018-05-12 18:06
@dn-medroom I have tried your PR it generates build successfully but when I tried to use `ngx-spinner` in my test project, it can't find `rxjs/operators.js`(shows 404).

**Comment by Napster2210** [comment] 2018-05-12 18:06
The solution for the same will be appreciated, thanx in advance.

**Comment by iamsaikat** [comment] 2018-05-22 11:28
have you tried this in the root project 
 `rxjs-5-to-6-migrate -p src/tsconfig.app.json`

**Comment by arimus** [comment] 2018-05-24 03:52
FWIW, the patch did work for me as well, but I still needed to make a tweak to the gulpfile to build successfully without errors.

```
diff --git a/gulpfile.js b/gulpfile.js
index 7f03ad0..ea029d8 100644
--- a/gulpfile.js
+++ b/gulpfile.js
@@ -55,14 +55,11 @@ gulp.task('inline-resources', function () {
 //   return Promise.resolve()
 // });
 gulp.task('ngc', function () {
-  return ngc({
-    project: `${tmpFolder}/tsconfig.es5.json`
-  })
-    .then((exitCode) => {
-      if (exitCode === 1) {
-        throw new Error('Compiler error');
-      }
-    });
+  return ngc([ '-p', `${tmpFolder}/tsconfig.es5.json` ], (exitCode) => {
+    if (exitCode === 1) {
+      throw new Error('Compiler error');
+    }
+  });
 });
```

...else I got the following error. Looks like it's due to the new angular versions. Probably another way to resolve, but modifying the ngc() call above got me building.

```
[20:46:42] 'ngc' errored after 1.44 ms
[20:46:42] TypeError: args.indexOf is not a function
    at module.exports (/Users/arimus/workspace/ngx-spinner/node_modules/minimist/index.js:44:14)
    at readNgcCommandLineAndConfiguration (/Users/arimus/workspace/ngx-spinner/node_modules/@angular/compiler-cli/src/main.js:68:45)
    at main (/Users/arimus/workspace/ngx-spinner/node_modules/@angular/compiler-cli/src/main.js:23:28)
    at Gulp.<anonymous> (/Users/arimus/workspace/ngx-spinner/gulpfile.js:58:10)
    at module.exports (/Users/arimus/workspace/ngx-spinner/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/arimus/workspace/ngx-spinner/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/arimus/workspace/ngx-spinner/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/arimus/workspace/ngx-spinner/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/Users/arimus/workspace/ngx-spinner/node_modules/run-sequence/index.js:86:16)
    at Gulp.onTaskEnd (/Users/arimus/workspace/ngx-spinner/node_modules/run-sequence/index.js:75:5)
ERROR: args.indexOf is not a function
```

**Comment by Napster2210** [comment] 2018-05-24 05:12
@iamsaikat `rxjs-5-to-6-migrate` doesn't work for me

**Comment by arimus** [comment] 2018-05-24 07:02
@Napster2210 I actually cloned from @waguirre 's repo, but I did a diff and it looks like the same things are in the pull request. I didn't have to run rxjs-5-to-6-migrate. I just:

- git clone
- npm install
- made the one change above for gulp
- gulp compile
- copied over the new files into existing project with angular 6

Everything is working for me. Let me know what issue you are having and I can try to reproduce and help get past it. It would be really nice to get this merged in, so feel free to hit me up and I'll assist.

**Comment by iamsaikat** [comment] 2018-05-24 07:08
@Napster2210 please check the pull request. Let me know if it will work or not .

**Comment by Napster2210** [comment] 2018-05-24 21:09
@iamsaikat In your PR, still facing the same issue.

**Comment by Napster2210** [comment] 2018-05-24 21:10
Currently, working on the major update will come up with major changes and some cool features with Angular 6 support. Thanx for using `ngx-spinner`

**Comment by arimus** [comment] 2018-05-25 01:19
Just a note that it would be nice if we could get this patch merged without any additional major changes, so that we can get unblocked on upgrading to Angular 6 without having to also re-factor the way we use ngx-spinner...unless the usage itself is close to the same and are forthcoming?

We're currently creating our own build with the changes in this pull request and using that local tarball dependency until we can get a new release with the fixes.

Thanks for ngx-spinner! nice component.

**Comment by Napster2210** [comment] 2018-05-26 09:19
@waguirre @dn-medroom @iamsaikat @arimus Resolved issues for the same. Published the latest version of `ngx-spinner` on npm([v6.0.0](https://www.npmjs.com/package/ngx-spinner)). Please check it out and thanx for your support.

**Closed by Napster2210** 2018-05-26 09:19 UTC
Labels: enhancement, help wanted

**Comment by arimus** [comment] 2018-05-26 10:35
:+1: I'll take a look after the weekend. much appreciated.

**Comment by iamsaikat** [comment] 2018-05-26 14:34
Thanks, will check tonight 👍
