### ISSUE TITLE
i use one spinner for all pages in my project, how to change options 

### ISSUE THREAD

**Issue by BahgatMashaly** [Napster2210/ngx-spinner#8] opened 2018-04-21 00:19 UTC
Hello Napster2210,

could you provide a way to change the spinner options from the ngx-spinner.service.ts ,  i use one element in app.componant.ts  .  
 i show and hide it from any page , but the problem that i need to change some options from other pages.

**Comment by Napster2210** [comment] 2018-04-21 18:55
Which options do you want to change? @BahgatMashaly Can you please tell me your scenario?

**Comment by Viveckh** [comment] 2018-04-21 21:38
I think being able to change values like "loading text" would be quite useful. Since a user would want that to display relevant information across the pages whereas the spinner's theme in general remains the same.

**Comment by BahgatMashaly** [comment] 2018-04-22 11:50
@Napster2210  i use one ngx-spinner  tag in my project , i put it in app.componant.html  and use static service  to show spinner  automatilcally with  every service call .   i need to pass some options like text when show spinner

**Comment by Napster2210** [comment] 2018-08-07 19:48
@BahgatMashaly @Viveckh I'm going to work on this in next few days and will be available in v6.2.0.

**Comment by ARCHAMO** [comment] 2018-08-16 13:47
Good morning.
I try to implement the component but by invoking this.spinner.show (); nothing is shown.

This in my packaje.json
![imagen1](https://user-images.githubusercontent.com/12633358/44212392-e195e780-a130-11e8-98b1-ef86743e4b96.PNG)
In the index.html I call my component.
![imagen2](https://user-images.githubusercontent.com/12633358/44212401-e6f33200-a130-11e8-89c6-21aa1e209218.PNG)

Inside the module where I am going to use it I realize the import.
![imagen3](https://user-images.githubusercontent.com/12633358/44212405-eb1f4f80-a130-11e8-8b57-576c1cb2de89.PNG)

Within the component, it asks me to define the provider.
![imagen4](https://user-images.githubusercontent.com/12633358/44212410-efe40380-a130-11e8-93d1-a3efec458b58.PNG)

In the template of componenete home. I define a button that is the one that calls the spinner.
![imagen5](https://user-images.githubusercontent.com/12633358/44212417-f4a8b780-a130-11e8-99ae-b182a84a2d7c.PNG)
![imagen6](https://user-images.githubusercontent.com/12633358/44212421-f70b1180-a130-11e8-95e4-fa1dfd7697cb.PNG)

Pressing on the button does nothing. What can I be doing wrong or what is missing?
I do not know if the tag of the component <ngx-spinner> </ ngx-spinner> should be defined in each template since I need it globally so that whenever it consumes my API it is displayed.

**Comment by Napster2210** [comment] 2018-08-16 15:04
Hello @ARCHAMO ,
You're calling `<ngx-spinner>` in wrong file, put it that code in your `app.component.html`.

**Comment by ARCHAMO** [comment] 2018-08-16 18:33
Thank you very much. I served but placing the label in each of the html where I want to show also make an import in each module to which the component belongs

Existence of way to define it as GLOBAL and be able to call it from any component.

My application is modular, I have several modules that inside have components and I want to be able to call it from any side with a single definition of TAG.

**Comment by Napster2210** [comment] 2018-08-16 18:43
So in that case you've `app.component.html`right?
It works as GLOBAL. So just use this TAG in that file only even though modular structure it'll work. From any component you can hide/show spinner.

**Comment by ARCHAMO** [comment] 2018-08-16 19:15
Make your suggestion but clicking the button does not show the spinner. The only way to see it is if in the template of the component itself I put the TAG.
The problem is that if I implement it that way, the day I have to modify it will touch me in all the components and it is not the idea.

**Comment by Napster2210** [comment] 2018-08-16 19:17
Can you please share your component code which contains button click event?

**Comment by ARCHAMO** [comment] 2018-08-16 20:11
**MY COMPONENT.TS**

import {Component, OnInit} from '@angular/core';
import {AuthService} from "../auth/auth.service";
import {GenerationExcelService} from '../../services/generation-excel.service';
import {GLOBAL} from '../../shared/global';
import {UTILS} from '../../shared/utils';
import {MethodApiRestService} from '../../services/method-api-rest.service';
import {ActivatedRoute, Router} from '@angular/router';
import {NotificationService} from '../../shared/utils/notification.service';
import {NgxSpinnerService} from "ngx-spinner";

declare let $: any;

@Component({
    selector: 'app-home',
    templateUrl: './home.component.html',
    styleUrls: ['./home.component.css'],
    providers: [
        NgxSpinnerService
    ]
})

export class HomeComponent implements OnInit {

    constructor(private spinner: NgxSpinnerService) {
    }

    ngOnInit() {
    }

    verSpinner() {
        this.spinner.show();

        setTimeout(() => {
            this.spinner.hide();
        }, 5000);    
    }
}

**MY HOME.MODULE.TS**
import {NgModule} from '@angular/core';
import {CommonModule} from '@angular/common';
import {homeRouting} from './home.routing';
import {SmartadminModule} from "../../shared/smartadmin.module";
import {HomeComponent} from "./home.component";
import {NgxSpinnerModule} from "ngx-spinner";

@NgModule({
    imports: [
        CommonModule,
        homeRouting,
        SmartadminModule,
        NgxSpinnerModule
    ],
    declarations: [HomeComponent]
})
export class HomeModule {
}

**MY APP.COMPONENT.HTML**
<ngx-spinner
        bdColor = "rgba(51, 51, 51, 0.8)"
        size = "large"
        color = "#bd1f1f"
        type = "ball-clip-rotate-pulse"></ngx-spinner>
<router-outlet></router-outlet>

**MY HOME.COMPONENT.HTML**
<div id="content">
    <button (click)="verSpinner()">Spinner</button>
</div>

**Comment by Napster2210** [comment] 2018-08-16 20:17
Have you tried to import `NgxSpinnerModule` in `app.module.ts` ??

**Comment by ARCHAMO** [comment] 2018-08-17 13:36
I have it imported into the app.modulo.ts and the tag I have it in app.component.ts, but the call I do it in a different component example home.component.ts but it does not come out, the only way that it comes out is that the tag place it in the home.component.html.
Is that why I conclude that the tag should be placed in all the html that are needed? or there is some way that the tag is only one.
Take into account that install version 1.2.0 because my application is in Angular 4 not know if this affects.

**Comment by iamavieira** [comment] 2018-10-23 03:01
@sahilkatia I also included a showcase on this PR. As soon as it gets merged(I hope, again), I'll set this showcase on stackblitz or plunker.

**Comment by KartikShankarappa** [comment] 2018-12-04 14:30
Any update on this ?

**Comment by Napster2210** [comment] 2019-01-23 22:44
@iamavieira @sahilkatia @KartikShankarappa I'll review and merge it soon.

**Closed** 2019-04-08 11:47 UTC
Labels: enhancement

**Comment by KartikShankarappa** [comment] 2019-04-08 13:52
Can we get a demo if this functionality on Stackblitz ?

**Comment by Napster2210** [comment] 2019-04-11 22:06
@KartikShankarappa Check it out latest version: https://www.npmjs.com/package/ngx-spinner/v/7.1.4

**Comment by PranayN1999** [comment] 2022-08-11 04:19
@Napster2210 What demo should I click to see single spinner across all components?

**Comment by PranayN1999** [comment] 2022-08-11 04:24
For this use case, I couldn't see spinner if I keep it in app.component.html

in app.component.html
`<ngx-spinner ></ngx-spinner>
<router-outlet></router-outlet>
`
